input:
  # Path to csv file containing message data in csv format relative to project directory
  messages_csv_filepath: data/disaster_messages.csv
  # Path to csv file containing message categories data in csv format relative to project directory
  categories_csv_filepath: data/disaster_categories.csv
  
output:
  # Path to database file to contain data resulting from processing csv files relative to project directory
  database_filepath: data/Messages.db
  # Path to model file relative to project directory
  model_filepath: models/disaster_model.pkl